[project]
name = "elma"
version = "0.1.0"
description = "Electrochemistry Lab Multi-frequency Acquisition: hardware drivers and live signal acquisition for the lab's multi-frequency impedance measurement setup."
authors = [
    {name = "Federico Scarpioni", email = "federicoscarpioni@gmail.com"},
]
maintainers = [
    {name = "Federico Scarpioni", email = "federicoscarpioni@gmail.com"},
]
readme = "README.md"
requires-python = ""
dependencies = [
    "numpy",
    "pyeclab",
    "pypicostreaming",
    "trueformawg",
    "npbuffer",
    "deistools @ git+https://github.com/federicoscarpioni/DEIStools.git",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/federicoscarpioni/elma.git"
Issues = "https://github.com/federicoscarpioni/elma/issues"


[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["B", "E", "F", "S", "UP"]
